from sqlalchemy import Column, Integer, String, Date, DateTime, DECIMAL, Time, Text
from backend.database import Base

class EmpDet(Base):
    __tablename__ = "xxits_emp_det_t"

    emp_id = Column(String(50), primary_key=True)
    name = Column(String(50))
    role_id = Column(String(100))
    dpt_id = Column(String(100))
    dom_id = Column(String(100))
    father_name = Column(String(50))
    mother_name = Column(String(50))
    dob = Column(String(100)) # Storing as string as per requirement "like 08-Feb-2001"
    age = Column(Integer)
    gender = Column(String(10))
    phone_number = Column(String(11))
    alt_phone_number = Column(String(11))
    blood = Column(String(100))
    p_mail = Column(String(50))
    mail_id = Column(String(50))
    address = Column(String(1000))
    p_address = Column(String(1000))
    aadhar_no = Column(String(25))
    pan_no = Column(String(15))
    passport_no = Column(String(20))
    end_date = Column(String(100))
    date_of_joining = Column(String(100))
    start_date_active = Column(String(100))
    aadhar = Column(String(100))
    pan = Column(String(100))
    passport = Column(String(100))
    passbook = Column(String(100))
    sslc = Column(String(100))
    hsc = Column(String(100))
    ug_degree = Column(String(100))
    ug_provisional = Column(String(100))
    pg_degree = Column(String(100))
    pg_provisional = Column(String(100))
    certificate = Column(String(100))
    password = Column(String(100))
    manager_id = Column(String(240))
    project_manager_id = Column(String(240))
    auth_signin = Column(Integer)
    auth_timer = Column(Integer)
    permission = Column(String(50))
    remaining_perm = Column(String(50))
    c_taken = Column(Integer)
    l_taken = Column(Integer)
    BDay_status = Column(String(240))
    Anniv_status = Column(String(240))
    l_assigned = Column(String(50))
    p_assigned = Column(String(50))
    add_role = Column(String(100))
    employment_type = Column(String(240))
    reporting_manager = Column(Integer)
    access_key = Column(String(100))
    role_type = Column(String(240))
    mod_id = Column(String(240))
    create_prv = Column(String(240))
    read_prv = Column(String(240))
    view_prv = Column(String(240))
    update_prv = Column(String(240))
    delete_prv = Column(String(240))
    rpd_id = Column(String(240))
    total_lop = Column(DECIMAL(5, 2))
    revised_month = Column(String(240))
    copy_address = Column(String(20))
    admin_prv = Column(String(240))
    hr_prv = Column(String(240))
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute8 = Column(String(240))
    assign_manager = Column(String(240))
    project_manager = Column(String(240))
    hr_spoc = Column(String(240))
    auth_key = Column(String(240))
    skill_id = Column(String(240))
    skill_rate = Column(String(240))
    attribute15 = Column(String(240))
    created_by = Column(String(100))
    creation_date = Column(DateTime)
    last_updated_by = Column(String(100))
    last_update_date = Column(DateTime)
    last_update_login = Column(String(255))


class CheckIn(Base):
    __tablename__ = "xxits_aruvi_check_in_t"

    check_in_id = Column(Integer, primary_key=True, autoincrement=True)
    emp_id = Column(String(20))
    in_time = Column(String(15))
    out_time = Column(String(15))
    Total_hours = Column(String(15))
    t_date = Column(Date)
    t_day = Column(String(15))
    month = Column(String(150))
    status = Column(String(150))
    # attributes...
    created_by = Column(String(150))
    creation_date = Column(DateTime)
    last_updated_by = Column(String(150))
    last_update_date = Column(DateTime)
    last_update_login = Column(String(150))


class Domain(Base):
    __tablename__ = "xxits_aruvi_domain_t"

    dom_id = Column(Integer, primary_key=True, autoincrement=True)
    domain_ref_no = Column(String(150))
    domain = Column(String(100))
    description = Column(String(100))
    status = Column(String(100))
    # attributes...


class EmpLeave(Base):
    __tablename__ = "xxits_aruvi_emp_leave_t"

    l_id = Column(Integer, primary_key=True, autoincrement=True)
    l_det_id = Column(Integer)
    emp_id = Column(String(100))
    leave_type = Column(String(100))
    from_date = Column(String(240))
    to_date = Column(String(240))
    days = Column(String(240))
    lop_days = Column(String(10))
    file = Column(String(240))
    reason = Column(String(1000))
    remarks = Column(String(240))
    status = Column(String(100))
    hr_action = Column(String(50))
    hr_approval = Column(String(100))
    admin_approval = Column(String(100))
    applied_date = Column(String(240))
    approved_by = Column(String(240))
    reporting_manager = Column(String(240))
    approver = Column(String(240))
    revision = Column(String(240))
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute8 = Column(String(240))
    attribute9 = Column(String(240))
    attribute10 = Column(String(240))
    attribute11 = Column(String(240))
    attribute12 = Column(String(240))
    attribute13 = Column(String(240))
    attribute14 = Column(String(2000))
    mail_message_id = Column(String(240))
    created_by = Column(String(100))
    creation_date = Column(DateTime)
    last_updated_by = Column(String(100))
    last_update_date = Column(DateTime)
    last_update_login = Column(String(255))


class EmpPermission(Base):
    __tablename__ = "xxits_aruvi_emp_permission_t"

    p_id = Column(Integer, primary_key=True, autoincrement=True)
    emp_id = Column(String(50))
    date = Column(Date)
    f_time = Column(Time)
    t_time = Column(Time)
    reason = Column(String(1000))
    remarks = Column(String(240))
    total_hours = Column(String(100))
    dis_total_hours = Column(String(100)) # LOP Hours
    available_hours = Column(String(100))
    status = Column(String(50), default="Pending")
    hr_approval = Column(String(100))
    admin_approval = Column(String(100))
    applied_date = Column(String(100))
    approved_by = Column(String(100))
    reporting_to = Column(String(100))
    permitted_permission = Column(String(100))
    lop_hours = Column(String(100))
    creation_date = Column(DateTime)
    last_update_date = Column(DateTime)
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute8 = Column(String(240))
    attribute9 = Column(String(240))
    attribute10 = Column(String(240))
    attribute11 = Column(String(240))
    attribute12 = Column(String(240))
    attribute13 = Column(String(240))
    attribute14 = Column(String(240))
    attribute15 = Column(String(240))


class LeaveDet(Base):
    __tablename__ = "xxits_leave_det_t"

    l_det_id = Column(Integer, primary_key=True, autoincrement=True)
    leave_type = Column(String(100))
    description = Column(String(240))
    emp_id = Column(String(100))
    total_leave = Column(String(240))
    available_leave = Column(DECIMAL(5, 2))
    availed_leave = Column(DECIMAL(5, 2))
    revised_year = Column(String(250))
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute8 = Column(String(240))
    attribute9 = Column(String(240))
    attribute10 = Column(String(240))
    attribute11 = Column(String(240))
    attribute12 = Column(String(240))
    attribute13 = Column(String(240))
    attribute14 = Column(String(240))
    attribute15 = Column(String(240))
    created_by = Column(String(100))
    creation_date = Column(DateTime)
    last_updated_by = Column(String(100))
    last_update_date = Column(DateTime)
    last_update_login = Column(String(255))


class WFHDet(Base):
    __tablename__ = "xxits_aruvi_wfh_det_t"

    wfh_id = Column(Integer, primary_key=True, autoincrement=True)
    from_date = Column(String(20), nullable=False)
    emp_id = Column(String(50), nullable=False)
    to_date = Column(String(20), nullable=False)
    days = Column(String(15), nullable=False)
    reason = Column(String(2000), nullable=False)
    status = Column(String(20), nullable=False)
    created_by = Column(String(250), nullable=False)
    creation_date = Column(DateTime, nullable=False)
    last_updated_by = Column(String(250), nullable=False)
    last_update_date = Column(DateTime, nullable=False)
    last_update_login = Column(String(250), nullable=False)
    approved_by = Column(String(250))
    remarks = Column(String(2000))


class OverTimeDet(Base):
    __tablename__ = "xxits_over_time_det_t"

    ot_id = Column(Integer, primary_key=True, autoincrement=True)
    emp_id = Column(String(50))
    ot_date = Column(String(20))
    from_time = Column(String(20))
    to_time = Column(String(20))
    duration = Column(String(20))
    approved_by = Column(String(50))
    approved_date = Column(String(100))
    applied_date = Column(String(20))
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute8 = Column(String(240))
    attribute9 = Column(String(240))
    attribute10 = Column(String(240))
    attribute11 = Column(String(240))
    attribute12 = Column(String(240))
    attribute13 = Column(String(240))
    attribute14 = Column(String(240))
    attribute15 = Column(String(240))
    created_by = Column(String(100))
    creation_date = Column(DateTime, nullable=False)
    last_updated_by = Column(String(100))
    last_update_date = Column(DateTime, nullable=False)
    last_update_login = Column(String(250), nullable=False)
    status = Column(String(50))
    remarks = Column(String(400))
    reason = Column(String(400))
    update_count = Column(Integer)


class TimesheetDet(Base):
    __tablename__ = "xxits_timesheet_det_t"

    t_id = Column(Integer, primary_key=True, autoincrement=True)
    bulk_id = Column(Integer)
    date = Column(String(20))
    day = Column(String(50))
    type = Column(String(100))
    project = Column(String(1000))
    total_hours = Column(String(11), nullable=False)
    activity = Column(String(4000))
    reason = Column(String(240))
    emp_id = Column(String(50))
    month = Column(String(50))
    working_hours = Column(String(20))
    status = Column(String(240))
    remarks = Column(String(350))
    revision = Column(String(10))
    approved_by = Column(String(100))
    approved_on = Column(DateTime)
    attribute_category = Column(String(240))
    attribute1 = Column(String(240))
    attribute2 = Column(String(240))
    attribute3 = Column(String(240))
    attribute4 = Column(String(240))
    attribute5 = Column(String(240))
    attribute6 = Column(String(240))
    attribute7 = Column(String(240))
    attribute15 = Column(String(240))
    created_by = Column(String(100))
    creation_date = Column(DateTime)
    last_updated_by = Column(String(100))
    last_update_date = Column(DateTime)
    last_update_login = Column(String(255))

